language: node_js

node_js: "lts/*"

cache:
  directories:
    - ~/.npm

stages:
  - name: test
  - name: deploy
    if: tag =~ ^v

jobs:
  include:
    - name: "node:lts"
      stage: test
      script:
        - yarn build
        - yarn test
    - name: "node:latest"
      node_js: "node"
      stage: test
    - name: "npm"
      stage: deploy
      script:
        - yarn build
      deploy:
        provider: npm
        cleanup: false
        email: $NPM_EMAIL
        api_token: $NPM_APIKEY
        edge: true
        on:
          tags: true

notifications:
  email: false
