language: node_js
os: linux
node_js: "lts/*"

cache:
  directories:
    - ~/.npm

stages:
  - name: lint
  - name: test
  - name: build
  - name: deploy
    if: tag =~ ^v

jobs:
  include:
    - name: "lint"
      stage: lint
      script:
        - yarn lint
    - name: "test:lts"
      stage: test
    - name: "test:latest"
      node_js: "node"
      stage: test
    - name: "build"
      stage: build
      script:
        - yarn build
      on:
        tags: false
    - name: "npm"
      stage: deploy
      script:
        - yarn build
      deploy:
        provider: npm
        cleanup: false
        email: $NPM_EMAIL
        api_token: $NPM_APIKEY
        edge: true
        on:
          tags: true

notifications:
  email: false
